backend:
  name: git-gateway
  repo: thenewdigitalschool/publishing-platform
  branch: master
  site_domain: https://tndsblog.netlify.com

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: pages
    label: Blog
    folder: "pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path,hint: 'E.g.: /chess-match'  }
      - { name: date, label: Date, widget: date }
      - { name: thumbnail, label: "Featured Image", widget: "image" }
      - { name: title, label: Title }
      - { name: published, label: Published }
      - { name: body, label: Body, widget: markdown }
