backend:
  name: git-gateway
  repo: thenewdigitalschool/publishing-platform

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: assets

collections:
  - name: pages
    label: Blog
    folder: "pages"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - { name: title, label: Title }
      - { name: published, label: Published }
      - { name: body, label: Body, widget: markdown }

